name: Build Pipeline

on: [ workflow_dispatch, push ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ghcr.io/graalvm/graalvm-ce:java17-21
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./mvnw -B clean verify
        name: run tests